name: Tests

on: pull_request

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v2
        with:
          python-version: 3.10.11

      - name: Install Python Poetry
        uses: abatilo/actions-poetry@v2.1.0
        with:
          poetry-version: 1.4.2

      - name: Configure poetry
        shell: bash
        run: python -m poetry config virtualenvs.in-project true

      - name: View poetry version
        run: poetry --version

      - name: Install dependencies
        run: python -m poetry install

      - name: Unit tests
        env:
          FINARY_EMAIL: ${{ secrets.FINARY_EMAIL }}
          FINARY_PASSWORD: ${{ secrets.FINARY_PASSWORD }}
        run: python -m poetry run pytest